tasks:
  - name: setup
    init: |
      sudo rm -rf /home/gitpod/.rustup/
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      rustup component add clippy
      rustup target add x86_64-unknown-linux-musl
      cargo build
      cargo build --release
      cargo install cargo-edit
      make run
