stages:          
  - build

build:       
  image: rust:1.63.0-slim
  stage: build
  timeout: 30 minutes
  artifacts:
    paths:
      - target/x86_64-unknown-linux-musl/release/system_perf
  script:
    - uname -a 
    - lscpu
    - apt update && apt install -y git make
    - rustup target add x86_64-unknown-linux-musl
    - rustup component add clippy
    - cargo build --release --target=x86_64-unknown-linux-musl 
    - cargo test --target=x86_64-unknown-linux-musl 
    - cargo clippy
    - cargo bench
    - make run


code:       
  image: ubuntu:20.04
  stage: build
  timeout: 10 minutes
  script:
    - apt update && apt install -y cloc
    - cloc src

build_centos7:       
  image: centos:7
  stage: build
  timeout: 30 minutes
  artifacts:
    paths:
      - hellosimd/target/release/hellosimd
      - target/release/system_perf
  script:
    - cat /etc/*release
    - lscpu
    - yum update -y && yum install -y epel-release && yum update -y && yum install -y curl git make gcc
    - curl https://sh.rustup.rs -sSf | sh -s -- -y
    - source "$HOME/.cargo/env"
    - rustup toolchain install nightly
    - make run
    - cd hellosimd
    - cargo +nightly test 
    - make run
